/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', 'system-ui', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'sans-serif'],
      },
      colors: {
        // GitHub Light Theme Colors (flattened for proper Tailwind parsing)
        'gh-canvas': '#ffffff',
        'gh-canvas-subtle': '#f6f8fa',
        'gh-canvas-inset': '#eff2f5',
        'gh-border': '#d1d9e0',
        'gh-border-muted': '#d8dee4',
        'gh-border-subtle': '#e1e4e8',
        'gh-fg': '#1f2328',
        'gh-fg-muted': '#656d76',
        'gh-fg-subtle': '#6e7781',
        'gh-accent': '#0969da',
        'gh-accent-emphasis': '#0550ae',
        'gh-accent-subtle': '#ddf4ff',
        'gh-accent-muted': '#54aeff',
        'gh-success': '#1a7f37',
        'gh-success-emphasis': '#116329',
        'gh-success-subtle': '#dafbe1',
        'gh-danger': '#d1242f',
        'gh-danger-emphasis': '#a40e26',
        'gh-danger-subtle': '#ffebe9',
        // GitHub Dark Theme Colors
        'ghd-canvas': '#0d1117',
        'ghd-canvas-subtle': '#161b22',
        'ghd-canvas-inset': '#010409',
        'ghd-border': '#30363d',
        'ghd-border-muted': '#21262d',
        'ghd-border-subtle': '#484f58',
        'ghd-fg': '#e6edf3',
        'ghd-fg-muted': '#8d96a0',
        'ghd-fg-subtle': '#6e7681',
        'ghd-accent': '#58a6ff',
        'ghd-accent-emphasis': '#1f6feb',
        'ghd-accent-subtle': '#388bfd26',
        'ghd-accent-muted': '#388bfd',
        'ghd-success': '#3fb950',
        'ghd-success-emphasis': '#238636',
        'ghd-success-subtle': '#2ea04326',
        'ghd-danger': '#f85149',
        'ghd-danger-emphasis': '#da3633',
        'ghd-danger-subtle': '#f8514926',
      },
      borderRadius: {
        gh: '6px',
        'gh-md': '8px',
        'gh-lg': '12px',
      },
      boxShadow: {
        'gh-sm': '0 1px 0 rgba(31, 35, 40, 0.04)',
        'gh': '0 3px 6px rgba(140, 149, 159, 0.15)',
        'gh-lg': '0 8px 24px rgba(140, 149, 159, 0.2)',
        'gh-dark-sm': '0 0 0 1px #30363d',
        'gh-dark': '0 3px 6px rgba(0, 0, 0, 0.4)',
        'gh-dark-lg': '0 8px 24px rgba(0, 0, 0, 0.6)',
      },
      animation: {
        'fade-in': 'fadeIn 0.2s ease-out',
        'slide-up': 'slideUp 0.3s ease-out',
        'pulse-soft': 'pulseSoft 2s ease-in-out infinite',
        'speaking': 'speaking 1.4s ease-in-out infinite',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { opacity: '0', transform: 'translateY(10px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        pulseSoft: {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.7' },
        },
        speaking: {
          '0%, 100%': { transform: 'scale(1)', opacity: '1' },
          '50%': { transform: 'scale(1.05)', opacity: '0.85' },
        },
      },
    },
  },
  plugins: [],
}
